First two chapters are tested
RedHatQuickCourses/rhods-intro pull request #44
Opened 2024-03-19 12:25 UTC by sarveshpandit

First two chapters are tested and suggested changes.

2024-03-20 14:36 UTC, rsriniva requested changes
excellent work Sarvesh! please review my comments and apply the changes. when fully done, ping me again for a quick approval. we can then merge and ask Rutuja to start

2024-03-20 14:36 UTC, rsriniva commented on modules/ROOT/pages/index.adoc
good catch. merge these changes!

2024-03-20 14:36 UTC, rsriniva commented on modules/chapter1/pages/section3.adoc
> +// Not understood the demo. Can be moved in next chapter before Lab.
OK. Good suggestion. Please cut the demo from here and move it to the appropriate place before final Lab

2024-03-20 14:36 UTC, rsriniva commented on modules/chapter1/pages/section3.adoc
> +// Need to add details such as name other settings.
If you think something is missing, please add details

2024-03-20 14:36 UTC, rsriniva commented on modules/chapter2/pages/section3.adoc
> +// Can we add separate page on deploy Minio?
no need. if the linked doc is good enough, then no need to duplicate

2024-03-20 14:36 UTC, rsriniva commented on modules/chapter2/pages/section3.adoc
> +// Exercise has not end objective or goal that we have achieved.
Please add appropriate objective to beginning and summarize at the end of the exercise

2024-03-20 14:36 UTC, rsriniva commented on modules/chapter2/pages/section4.adoc
> +//Need more information on the objectives and goals of the lab.
hmm - maybe the objective is to learn these basic concepts of projects, permissions, workbenches, env vars and connections? please suggest alternative objectives

2024-03-20 14:36 UTC, rsriniva commented on modules/chapter2/pages/section4.adoc
> +// Login as user1 is missing in the instruction.
please add instructions for log in

2024-03-20 14:36 UTC, rsriniva commented on modules/chapter2/pages/section4.adoc
> +// When to run the command is missing -  "$ oc create -f https://raw.githubusercontent.com/RedHatQuickCourses/rhods-qc-apps/main/1.intro/chapter2/lab/group.yaml"
please add it

2024-03-20 14:37 UTC, rsriniva commented
Other adoc files with no review comments - please merge the suggestions because I think they are good

2024-03-22 04:56 UTC, rsriniva approved these changes
Approved. please merge after addressing my comments

2024-03-22 04:56 UTC, rsriniva commented on modules/ROOT/pages/index.adoc
> +// I see Operator version as 2.8.0, can we change from 2.4 to 2.8.0?
yes. please update

2024-03-22 04:56 UTC, rsriniva commented on modules/chapter2/pages/section4.adoc
> +// This is not working as expected. I get this error - "ls: cannot access 'my_model/pytorch_model.bin': No such file or directory"
not sure. none of the other users have complained. please open an issue

2024-03-22 05:06 UTC, sarveshpandit commented on modules/ROOT/pages/index.adoc
> +// I see Operator version as 2.8.0, can we change from 2.4 to 2.8.0?
Okay.

2024-03-22 05:29 UTC, merged